USE [Dealer]
GO
--insertar en la tabla de proveedores
INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Honda Dominicana','00155415','HondaDominicana@gmail.com','Av. John F. Kennedy, Santo Domingo')
	 
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Volkswagen Group','002472365','VolkswagenGroup@gmail.com','Av. Santiago de lo caballeros')
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Alianza','0078943512','Alianza@gmail.com','Av. Duarte')
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Toyota Group','0025478946','ToyotaGroup@gmail.com','Av.correa y sidron')
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('General Motors','0035715934','GeneralMotors@gmail.com','Av. Las Americas')
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Hyundai-Kia','0078465239','HyundaiKia@gmail.com','Av. Romana')
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Ford Group','0096325417','FordGroup@gmail.com','Av. 35')
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('FCA','0085126473','FCA@gmail.com','Av. Rafael thomas Fernandez')
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Honda Motor','0028513648','HondaMotor@gmail.com','Av.juan pablo Duarte')
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Mercedes-Daimler','0034564896','MercedesDaimler@gmail.com','Av. San martín')

--insertar en la tabla de Cliente
INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Ramon','Tolentino','0013458464','Naco city')

	 INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Francis','0015654512','francispepe@gmail.com','Bellas vistas')
	 INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Rouse','001248562','Rousematalena@gmail.com','Charles de Gaulle')
	 INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Pepe','0028546213','pepetolentin@gmail.com','Ercilia Pepín')
	 INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Edgar Dominguez','0035991746','Edgarmomon@gmail.com','Horacio Vázquez')
	 INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Ronald','005598742','ronaldtabult@gamil.com','Pro. Juan Bosch')
	 INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Williams','0014884562','williamsperez@gmail.com','Centro de los Héroes')
	 INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Natali','0011479562','natali99@gmail.com','Ulises Francisco Espaliat')
	 INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Domingo manuel','0022684485','Domingo135@gmail.com','Amin Abel')


--insertar en la tabla de automovil
INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],[ano])
     VALUES ('Honda','Accord','6c','4','Sedan','K54854s284f6','1','2015')

	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],[ano])
     VALUES ('Toyota','corola','1800c','4','Sedan','k545445v55','7','2010')
	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],[ano])
     VALUES ('Audi','A1Sportback','3c','4','Citycarver','K578278d545','9','2012')
	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],[ano])
     VALUES ('Ferrari','458 italia','9c','4','ferrari F8','k786424df6845','10','2019')
	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],[ano])
     VALUES ('Ford','EciSport','6c','4','UVopickup.','k75554s54','1','2020')
	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],[ano])
     VALUES ('Honda','Accord','5c','4','turismo','k789545fs56','2','2003')
	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],[ano])
     VALUES ('Hyundia','Bayon','4c','4','hatchback','k5625df6542','3','2015')
	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],[ano])
     VALUES ('Jeep','Cherokee','5c','4','Cherokee','Kfdf4521246','6','2017')
	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],[ano])
     VALUES ('Kia','Carens','4c','4','Carens','K54124f5f','1','2017')
	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],[ano])
     VALUES ('Lamborghini','Aventador','498c','2','Roadster','Kf545f5444f','5','2020')

--Insertar en la table Inventario
INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES ('Retrovisor derecho','2','Honda Civic 2010','1')           
	 
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES ('carrocería de 5 puertas','3','Toyota Corolla 2010','2')           
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES ('propulsor','4','AudiSportback','37')           
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES ('Convertible de 2 puertas ','7','Ferrari, 458 italia','4')           
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES ('Tracción 4x4 ','8','Ford EciSport','5')           
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES ('4 puertas','1','Honda Accord','68')           
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES ('Maletero: 411/1.205 litros ','2','Hyundai Bayon','7')           
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES ('CarroceríaSUV Grande','3','Jeep Cherokee','8')           
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES ('Altura: 1,70 metros','5','Kia Carens','9')           
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES ('POTENCIA MÁXIMA740 CV ','4','Lamborghini Aventador','10')           

--Insertar en la tabla de Venta
INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES ('1','1','950000.50','T')

	 INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES ('33','99','10000000','T')
	 INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES ('66','88','305440055','T')
	 INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES ('99','99','595530005','T')
	 INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES ('7','2','95000060','T')
	 INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES ('10','11','2000000','T')
	 INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES ('5','9','450065090','T')
	 INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES ('22','79','1453773','T')
	 INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES ('3','8','428967','T')

GO


